name: "Ready Markdown Blog"
description: "GitHub Action to generate a blog from markdown and publish website to GitHub Pages"
author: "@dan-frank"

inputs:
  GITHUB_TOKEN:
    description: "Only customise this token if you want to push to another GitHub repository"
    required: true
    default: ${{ github.token }}
  URL:
    description: Custom URL to use instead of default GitHub pages URL
    required: false
  LOGO_URL:
    description: URL for site logo
    required: false
  FAVICON_URL:
    description: URL for site favicon
    required: false
  BLOG_NAME:
    description: Blogs name
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
