name: "Ready Markdown Blog"
description: "GitHub Action to generate a blog from markdown and publish website to GitHub Pages"
author: "@dan-frank"

inputs:
  GITHUB_TOKEN:
    description: "Only customise this token if you want to push to another GitHub repository"
    required: true
    default: ${{ github.token }}

runs:
  using: "node16"
  main: "dist/index.js"
