name: "Ready Markdown Blog"
description: "GitHub Action that generates a blog from markdown and hosts on GitHub Pages"
author: "@dan-frank"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
